open! Import

(** [infer_exp exp] returns the constraint generated by [exists 'a. [| exp : 'a |]]. *)
val infer_exp : options:Omniml_options.t -> Ast.expression -> unit Constraint.t

(** [infer_str str] returns the constraint generated by [[| str |]] *)
val infer_str
  :  options:Omniml_options.t
  -> Ast.structure
  -> Typed_ast.signature Constraint.t

(** [check cst] checks that [cst] is satisfiable and returns its semantic value.

    @raises Omniml_error.T if the constraint is unsatisfiable *)
val check : options:Omniml_options.t -> ?range:Range.t -> 'a Constraint.t -> 'a
