name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16 
        with:
          name: mlsus
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix --version
      - name: Format
        run: nix --accept-flake-config fmt -- --ci
      - name: Build and Check 
        run: nix --accept-flake-config flake check -j auto
      